image: php:7.1.1

pipelines:
  default:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
         - export IMAGE_NAME=web-tp3/docker:$BITBUCKET_BRANCH
         # build the Docker image (this will use the Dockerfile in the root of the repo)
         - docker build -t $IMAGE_NAME .
         # authenticate with the Docker Hub registry
         - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
         # push the new Docker image to the Docker registry
         #- docker push $IMAGE_NAME
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          #- composer --dev --stability=dev create-project web-tp3/tp3_installer
