image: php:7.1.1

pipelines:
  default:

    - step:
        name: Deploy to testing
        image: docker:stable
        deployment: test
        script:
          # for database start with composer
          - ls -an
          - apk add --no-cache py-pip bash
          - pip install --no-cache-dir docker-compose
          - docker-compose -f docker-compose.yml up
          - docker exec typo3 cp -r . typo3:/var/www/html
          - docker-compose -f docker-compose.yml down

    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export webtp3/docker:$BITBUCKET_BRANCH

          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME .
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          # push the new Docker image to the Docker registry
          #- docker push $IMAGE_NAME