typo3:
  build: .
  links: 
   - db
  ports:
   - "80:80"
  environment:
    DB_NAME: typo3
    DB_USER: root
    DB_PASS: my-secret-pw
    DB_HOST: "db"
    DB_PORT: "3306"
db:
  image:  webtp3/tp3sql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
  ports:
    - "3306:3306"
adminer:
  image: adminer
  restart: always
  ports:
    - 8080:8080